dist: trusty
addons:
  chrome: stable
  firefox: latest
sudo: false
branches:
  only:
    - develop
language: node_js
node_js: lts/*
env:
  - MOZ_HEADLESS=1
install:
  - npm install
script:
  - npm run test
